import { clipboard } from 'electron';
import { EventEmitter } from 'events';

// macOS pasteboard types that indicate sensitive or programmatic clipboard content.
// ConcealedType: password managers (1Password, Bitwarden, Keychain, etc.)
// AutoGeneratedType: OS-level programmatic writes that shouldn't be archived.
const PRIVATE_FORMATS = [
  'org.nspasteboard.ConcealedType',
  'org.nspasteboard.AutoGeneratedType',
];

export class ClipboardMonitor extends EventEmitter {
  constructor(interval = 500) {
    super();
    this.interval   = interval;
    this._timer     = null;
    this._last      = '';
    this._lastFormats = '';
    this._paused    = false;
  }

  start() {
    this._last        = clipboard.readText();
    this._lastFormats = clipboard.availableFormats().join(',');

    this._timer = setInterval(() => {
      if (this._paused) return;
      const formats    = clipboard.availableFormats();
      const formatSig  = formats.join(',');
      const text       = clipboard.readText();

      // Privacy: skip concealed or auto-generated clipboard entries.
      // Leave _last unchanged so the next real copy is always captured.
      if (PRIVATE_FORMATS.some(t => formats.includes(t))) {
        this._lastFormats = formatSig;
        return;
      }

      // H-6: detect image-only copies (no text, but image format present)
      const hasImage = formats.some(f => f.startsWith('image/'));
      if (hasImage && text === '' && formatSig !== this._lastFormats) {
        this._lastFormats = formatSig;
        this._last = '';
        this.emit('change', '[Image]', 'image');
        return;
      }

      if (text && text !== this._last) {
        this._last        = text;
        this._lastFormats = formatSig;
        this.emit('change', text, undefined);
      }
    }, this.interval);
  }

  pause()  { this._paused = true; }
  resume() { this._paused = false; }

  stop() {
    if (this._timer) { clearInterval(this._timer); this._timer = null; }
  }
}
